# Generated by Django 5.2.5 on 2025-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_herb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='other_category_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='category',
            field=models.CharField(choices=[('leaf', 'Leaf'), ('root', 'Root'), ('seed', 'Seed'), ('flower', 'Flower'), ('bark', 'Bark'), ('fruit', 'Fruit'), ('stem', 'Stem'), ('other', 'Other')], max_length=50),
        ),
    ]
