# Generated by Django 5.2.5 on 2025-10-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_herb_other_category_explanation_alter_herb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='ailments',
            field=models.TextField(blank=True, help_text="Comma-separated list of ailments this herb treats, e.g., 'headache, fever'", null=True),
        ),
    ]
