# Generated by Django 5.2.5 on 2025-10-09 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='herb',
            unique_together={('name', 'uses', 'created_by')},
        ),
    ]
