# Generated by Django 5.2.5 on 2025-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_herb_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='herb_images/'),
        ),
    ]
